### ISSUE TITLE
Variant type deduction

### ISSUE THREAD

**Issue by LtJulius** [lawmurray/doxide#13]
Ran into another problem.

While i was trying to clone a repo with the build html pages, it was failing, because of a too long creation path:
```log
public/hg/ConstantNodeParameterTypeStorage/ConstantNodeParameterTypeStorage/ConstantNodeParameterTypeStorage/ConstantNodeParameterTypeStorage/ConstantNodeParameterTypeStorage/ConstantNodeParameterTypeStorage/ConstantNodeParameterTypeStorage/ConstantNodeParameterTypeStorage/ConstantNodeParameterTypeStorage/ConstantNodeParameterTypeStorage/ConstantNodeParameterTypeStorage/ConstantNodeParameterStorage/index.html
```

So I checked the created docs directory of doxide and found the same folder structure with the related markdown files and sub-folders.

```log
~/git/docs/hg/ConstantNodeParameterTypeStorage/ConstantNodeParameterTypeStorage/ConstantNodeParameterTypeStorage/ConstantNodeParameterTypeStorage/ConstantNodeParameterTypeStorage/ConstantNodeParameterTypeStorage/ConstantNodeParameterTypeStorage/ConstantNodeParameterTypeStorage/ConstantNodeParameterTypeStorage/ConstantNodeParameterTypeStorage/ConstantNodeParameterTypeStorage/ConstantNodeParameterStorage.md
```

The related source code:`
```cpp
typedef _STD variant<
    /**/
    ConstantNodeParameterTypeStorage<NodeLinkValueType::u8>::type,
    ConstantNodeParameterTypeStorage<NodeLinkValueType::u16>::type,
    ConstantNodeParameterTypeStorage<NodeLinkValueType::u32>::type,
    ConstantNodeParameterTypeStorage<NodeLinkValueType::u64>::type,
    /**/
    ConstantNodeParameterTypeStorage<NodeLinkValueType::f32>::type,
    ConstantNodeParameterTypeStorage<NodeLinkValueType::f64>::type,
    /**/
    ConstantNodeParameterTypeStorage<NodeLinkValueType::f32vec2>::type,
    ConstantNodeParameterTypeStorage<NodeLinkValueType::f32vec3>::type,
    ConstantNodeParameterTypeStorage<NodeLinkValueType::f32vec4>::type,
    /**/
    ConstantNodeParameterTypeStorage<NodeLinkValueType::f32mat2x2>::type,
    ConstantNodeParameterTypeStorage<NodeLinkValueType::f32mat3x3>::type,
    ConstantNodeParameterTypeStorage<NodeLinkValueType::f32mat4x4>::type
    /**/
    //ConstantNodeParameterTypeStorage<NodeLinkValueType::color>::type // Does already exists as `f32vec4`
> ConstantNodeParameterStorage;
```

So I guess the variant is a problem :?
Anyway, if you need more of the source code, msg me again.

Sorry for the inconvenience.

**Comment by lawmurray** [comment]
Looks like the `_STD` is producing a parse error. I'm guessing that's a macro that expands to `std::`?

**Comment by lawmurray** [comment]
I've applied some updates so that parsing errors such as this produce a warning message and the culprit file is skipped. That's just for better communicating with the user what is going on. Still working on ways to recover in this situation.

The fundamental issue is that tree-sitter does not do macro expansion, so programs that are not syntactically valid without macro expansion (which is what seems to be happening here) may require some special treatment. Working on it.

**Comment by lawmurray** [comment]
Related: tree-sitter/tree-sitter-cpp#136

**Comment by lawmurray** [comment]
I've tightened the query for typedefs in 9534721, which acts as an appropriate recovery from the parse error, and fixes this particular case. This macro expansion issue may arise again and require further tweaks. Tagged as `v0.0.3`, [packages rebuilding](https://app.circleci.com/pipelines/github/lawmurray/download.indii.org/31/workflows/c578c166-8f4f-4a93-ac9e-d1f00ffad06d).

**Comment by lawmurray** [comment]
It respects namespaces, yes, including C++ nested namespace declarations like `namespace a::b::c`. If you use `@ingroup`, however, it will shift an entity out of its namespace and into the given group.

I can do something to make it quieter. But despite the warnings, is it producing the expected documentation?

**Comment by lawmurray** [comment]
If you're happy to share a larger chunk of your codebase that captures these issues I can have a look. Just point me to the repo, or you can email an archive (address on my profile).

**Comment by lawmurray** [comment]
Closing the ticket as the original issue is resolved, although still some thinking to do on handling macros.
