### ISSUE TITLE
Functions returning reference types are not included

### ISSUE THREAD

**Issue by SonnyBonds** [lawmurray/doxide#16]
A function that returns a reference type, e.g. `int f(int x, int y);`  does not get included in the documentation.

**Comment by lawmurray** [comment]
Thanks @SonnyBonds. This is a curious one, it seems as though Tree-sitter parses functions that return references differently, and in fact functions that return pointers differently too. The same applies to variable types.

Working on it.

**Comment by lawmurray** [comment]
Fixed this one. New release pending, but have added to the [demo](https://doxide.org/demo/parsing/) on the website so you can see this working now.

Thanks @SonnyBonds for the report, nice catch!

**Comment by lawmurray** [comment]
Included in new v0.2.1 release, [build underway](https://app.circleci.com/pipelines/github/lawmurray/download.indii.org/57/workflows/8c803766-8f7a-4679-a0ba-7a68f6c6300c).
