### ISSUE TITLE
Doc comments not ending with a period '.' don't get a summary at all

### ISSUE THREAD

**Issue by SonnyBonds** [lawmurray/doxide#19]
It seems like the short summary of an entity is determined by the text before the first '.' character. If the documentation comment doesn't have one (e.g. `/** Some field */`) it doesn't get a summary at all.

This is kind of simple to work around by just adding a '.', but conversely it also stops the summary at the first period in cases where maybe multiple sentences should be in the summary. Or, as in my case, this: `Extension of the output filename, including dot '.' character.`

Maybe defining the summary as the first line of the documentation comment could be better? That was my initial expectation at least, similar to e.g. git commit messages.

**Comment by lawmurray** [comment]
Thanks @SonnyBonds. This is the expected behavior at this stage. It works as for the autobrief feature in Doxygen (e.g. see [here](https://www.doxygen.nl/manual/docblocks.html)), where the first sentence is taken. There is support for a `@brief` command as well that lets you manually override, e.g.

```cpp
/**
 * @brief Brief description, not necessarily ending with a dot
 *
 * Full description
 */
int f(int x, int y);
```

**Comment by SonnyBonds** [comment]
Ah, thank you. That works.

Somewhat unexpected if I do `/** @brief Some brief. */`the `*/` will be included in the brief. Not a huge problem and easy to work around, just wanted to mention it.

**Comment by lawmurray** [comment]
Thanks @SonnyBonds, will look info this last point.
