### ISSUE TITLE
Add C++ style doxygen comments

### ISSUE THREAD

**Issue by ambihelical** [lawmurray/doxide#21]
It would be useful for migration purposes if doxide supported doxygen-style C++ // comments, namely:

* //! or /// introduces documentation block comments
* //!< or ///< introduces member comments, after the member

**Comment by lawmurray** [comment]
Thanks for posting @ambihelical, will see what we can do here.

**Comment by nalyd88** [comment]
Hello, I have the same issue. I would like to use doxide but I would need to refactor all the comments in my entire codebase! My code uses the /// style comments. I think the update would need to be [here](https://github.com/lawmurray/doxide/blob/9abd29a25ee37cd5486b1349661ddcc9a384fdbb/src/parser/Token.hpp#L28) but I don't speak regex lol. A good option may be a CLI flag to select which format of comments you want to parse? Thanks!

**Comment by lawmurray** [comment]
Thanks @nalyd88. You're right that some updates will be needed there, but also in the tree-parser queries [here](https://github.com/lawmurray/doxide/blob/9abd29a25ee37cd5486b1349661ddcc9a384fdbb/src/parser/Language.cpp), as I presume multiline `///` comments are parsed as multiple comments. My sense is this shouldn't be too difficult, I'm having a look now.

**Comment by lawmurray** [comment]
Latest commit adds support for starting documentation comments before entities with `/*!`, `///` and `//!`. Needs a little more testing, and I'll have a look at end-of-line comment support too.

**Comment by lawmurray** [comment]
Also now support for end-of-line comments in all of the styles suggested by @ambihelical. New release on the way.

**Comment by lawmurray** [comment]
Now released as [v0.3.0](https://github.com/lawmurray/doxide/releases/tag/v0.3.0), Linux and Homebrew (Mac) packages are updated, Chocolatey (Windows) packages generally take around week for moderator review.

Thanks @ambihelical and @nalyd88 for the suggestion. This may require some further iteration to get the behavior right for your code bases, would be good to hear how to get on with this update.

**Comment by lawmurray** [comment]
Will close as resolved for now, but further feedback on this welcome.

**Comment by nalyd88** [comment]
In my limited testing the new feature seems to work. It pulls in documentation from a mix of styles actually. My only issue was that I had to add `add_subdirectory(contrib/libyaml)` to the CMakeLists.txt in order to build. Thanks!

**Comment by lawmurray** [comment]
Great, thanks for the update @nalyd88 ! Let me see if I can iron out that build from source issue. Which platform are you on?

**Comment by nalyd88** [comment]
I built and tested on macOS using clang 14 and cmake 3.27.7.

________________________________
