### ISSUE TITLE
Error while compiling doxide

### ISSUE THREAD

**Issue by pierre-24** [lawmurray/doxide#33]
Hello,

I'm trying to compile the program for Fedora 39, as it is not (yet?) in the repository. I used the instructions from the README and went:

```
git clone https://github.com/lawmurray/doxide --recurse-submodules
cd doxide
mkdir build
cd build
cmake ..
cmake --build .
```

Sadly, the last command resulted in an error on the very first step:

```
[  8%] Building C object CMakeFiles/doxide.dir/contrib/tree-sitter/lib/src/lib.c.o
In file included from /home/pierre/code/doxide/contrib/tree-sitter/lib/src/././unicode.h:13,
                 from /home/pierre/code/doxide/contrib/tree-sitter/lib/src/./lexer.c:5,
                 from /home/pierre/code/doxide/contrib/tree-sitter/lib/src/lib.c:11:
/home/pierre/code/doxide/contrib/tree-sitter/lib/src/././unicode/utf8.h:37:10: fatal error: unicode/umachine.h: No such file or directory
   37 | #include "unicode/umachine.h"
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/doxide.dir/build.make:76: CMakeFiles/doxide.dir/contrib/tree-sitter/lib/src/lib.c.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/doxide.dir/all] Error 2
gmake: *** [Makefile:156: all] Error 2
```

I checked, and `umachine.h` is where it is supposed to be, so I'm assuming that I did something wrong in previous steps. Would you have any idea?

Thanks in advance :)

**Comment by lawmurray** [comment]
Thanks for the report @pierre-24. Can you try installing `libicu-devel`? I think that may be where the header resides on Fedora.

I'll have a look at adding a Fedora 39 repository.

**Comment by pierre-24** [comment]
Oh, I see. I'm definitely not a specialist of CMake, but it would probably be better to add stuffs that are `contribs/` as a [`subproject`](https://stackoverflow.com/questions/61007492/cmake-using-add-subproject-with-a-library-using-include-ends-up-in-wrong-relati) (?) so that the actual codes (and includes) from theses project at that specific commit are used rather than system libraries (since this could break if for some reasons headers of system and the one you expect are different). Another option would be to declare things like `libyaml` as an explicit dependency and remove them from `contribs/` (since, in practice, it would work as well). 

In the end, I installed `libicu-devel` and also had to install `libyaml-devel`, but now it works :)

**Comment by lawmurray** [comment]
Thanks @pierre-24, good to hear that it's working.

Yes, I think there are better ways to handle dependencies with CMake, although I'm learning it as I go too (I've used GNU Autotools until now, thought I'd try CMake for this project to better support Windows users). Improvements welcome. The current setup is a mash up of getting Linux builds to work with system libraries where available, Mac builds to work with Homebrew packages where available, but resorting to submodules in the `contrib/` directory for Windows builds (something like vcpkg would be an alternative). For Linux builds, I would prefer to use system libraries where available, which is generally the spirit for Linux packaging as it facilitates security patches via shared libraries. You're right that system library changes may break builds, but at that gets caught by the packaging pipeline (in my [download.indii.org](https://github.com/lawmurray/download.indii.org) repo, running on [CircleCI](https://app.circleci.com/pipelines/github/lawmurray/download.indii.org)).

Working on that Fedora 39 repo by the way.

**Comment by pierre-24** [comment]
Ok, that explains why there are that much submodules. Then, I advise you to add to the documentation that for linux, one should install the system packages (you might not have to list the exact packages names, just link to the documentation of libyaml and libicu). It will help future person that do not have a system yet supported ;)

**Comment by lawmurray** [comment]
For now, added some further instructions on installing requirements to the README.md.

**Comment by lawmurray** [comment]
And a Fedora 39 repository is now [available](https://doxide.org/installation/).

**Comment by pierre-24** [comment]
Thanks, that should do the trick :)
