### ISSUE TITLE
Error while handling structure

### ISSUE THREAD

**Issue by pierre-24** [lawmurray/doxide#34]
I want to make a bug report.

If one use `doxide` on this code:

```c
/**
* That's a test.
 */
struct test_ {
  /// A first variable
  int a;
  
  /// a second variable
  FILE* f;
};
```

The second variable does not get documented. 
I think the problem comes from the use of pointers, since it also does not work with, say, `char*`.
More strange, while using this code:

```c
/**
* That's a test.
 */
struct test_ {
  /// A first variable
  int a;
  
  /// a second variable
  FILE* f;
};

typedef struct test_ test; // yeah, it is C, typedef are not automatic
```

... Then the info for `FILE* f` appears in the description of the `typedef`.

**Comment by lawmurray** [comment]
Possibly related to #16. The C and C++ grammars for Tree-sitter parse pointer and reference members differently to others. Likely an issue around that.

**Comment by lawmurray** [comment]
Actually this looks to be a regression of #16. The test cases on the website are showing the error too: https://doxide.org/demo/parsing/ClassWithMembers/#x
