### ISSUE TITLE
Using /// comments break paragraphs

### ISSUE THREAD

**Issue by Tim-Evans-Seequent** [lawmurray/doxide#38]
I've found I can't use paragraphs when inside `///` doc-comments. Using this header file:

```c++
namespace example {

/** First function
 *
 * This one uses block comments and multiple paragraphs and such can be used.
 *
 * #### Example
 *
 * ```c++
 * first();
 * ```
 */
void first();

/// Second function
///
/// This one uses single-line comments and the paragraphs are broken.
///
/// #### Example
///
/// ```c++
/// second();
/// ```
void second();

} // namespace example
```

The documentation for the first function is correct, but the second does not, getting all its paragraphs jammed together:
![image](https://github.com/lawmurray/doxide/assets/30094120/1dcacba7-05e2-4260-b2af-1d05cf21be08)

This might be Windows specific, as I haven't been able to test it on Linux. It doesn't seem to be end-of-line related though.

**Comment by Tim-Evans-Seequent** [comment]
Attaching the generated markdown file.
[index.md](https://github.com/lawmurray/doxide/files/14105635/index.md)

**Comment by lawmurray** [comment]
Thanks for the report @Tim-Evans-Seequent! Seems to be a bug, yes. Looking into it.

**Comment by lawmurray** [comment]
Got it. New release on the way with the fix.
