### ISSUE TITLE
Add version flag to the executable

### ISSUE THREAD

**Issue by jkhoogland** [lawmurray/doxide#61]
Hi,
it would be great if there was a `--version` flag available.
Is it possible to add this?
Thanks!

**Comment by lawmurray** [comment]
Thanks for the suggestion @jkhoogland, should be straightforward enough.

If anyone (including yourself) has bandwidth to add this before I do, the ideal approach would be to get the version as defined in the CMakeLists.txt file and define a macro for it (if CMake does not automatically define such a macro, I know GNU Autotools does, never done this with CMake though). The macro could then be used for the output of the program when `--version` is given.

The CircleCI [packaging pipeline](https://github.com/lawmurray/download.indii.org/blob/main/.circleci/config.yml) already updates the version number in CMakeLists.txt when packaging, so it should be set there already. The release tarballs on GitHub are snapshots of a tag, however, and have the version number hardcoded to 0.0.0. So will need to do something about that too. Maybe a manual update of that when releasing will be necessary, but I prefer to automate these things if possible.

**Comment by jkhoogland** [comment]
Added a PR: https://github.com/lawmurray/doxide/pull/64

**Comment by jkhoogland** [comment]
Updated with minimal logic for use of system yaml if available: 2521c0c95fabcc726c424f56e2c01fba662fde16

**Comment by lawmurray** [comment]
Closing now as resolved by the merge of #64. Thanks to @jkhoogland again for the addition!
