### ISSUE TITLE
Link in the first sentence of the documentation comment

### ISSUE THREAD

**Issue by Bzero** [lawmurray/doxide#68]
It is recommended to make the first sentence of the documentation comment usable as a brief description which is then used in the overview table. When the first sentence contains a markdown link containing punctuation (which about every domain name does) the first sentence is however not detected correctly and the whole documentation comment is used as a brief description.

For example, in the following code snipped the whole documentation comment is used as brief description:

```
///Some text with a [link](https://example.com). Some more text.
int example = 0;
```

**Comment by lawmurray** [comment]
Thanks for the report @Bzero!

A quick fix would be updating the regular expression that grabs the first sentence to accommodate some shallow delimiters like `[]()` for links. A longer term fix would be incorporating a Markdown parser.

**Comment by Bzero** [comment]
I would think adapting the regular expression should be able to cover most cases without the need of a heavy Markdown parser. I will create a pull request to allow links in the brief description.
