### ISSUE TITLE
Add Doxide to Arch Linux AUR

### ISSUE THREAD

**Issue by lawmurray** [lawmurray/doxide#8]
There is a [PKGBUILD](https://github.com/lawmurray/doxide/blob/main/PKGBUILD) in the repository as a start, although this will need testing.

**Comment by tocic** [comment]
https://aur.archlinux.org/packages/doxide

**Comment by lawmurray** [comment]
This is great, thanks for putting it together @tocic!

**Comment by lawmurray** [comment]
Have also now added a link on the [website](https://doxide.org/installation/).
